[package]
name = "daylight"
version = "1.0.0"
authors = ["Nathan Osman <nathan@quickmediasolutions.com>"]

[dependencies]
bodyparser = "0.8.*"
iron = "0.6.*"
mount = "0.4.*"
router = "0.6.*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
staticfile = "0.5.*"
sunrise = "1.0.0"
